apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskblog-deployment
  labels:
    app: flaskblog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskblog
  template:
    metadata:
      labels: 
        app: flaskblog
    spec:
      containers:
      - name: flaskblog
        image: ansarshaik965/flasktesting
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: flaskblog-service
spec:
  type: NodePort
  selector:
    app: flaskblog
  ports:
    - port: 5000
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 5000
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
