apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-deployment
  labels:
    app: trivy

spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy

  template:
    metadata:
      labels:
        app: trivy
    spec:
      containers:
      - name: trivy-container
        image: aquasec/trivy:latest
        command: ["trivy", "server", "--listen", ":8080"]
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: trivy-service
spec:
  type: NodePort
  selector:
    app: trivy
  ports:
    - protocol: TCP
      port: 8080  # Port on the Service (can be different from containerPort)
      targetPort: 8080  # Port on the Pod where Trivy is listening
      nodePort: 30010

